### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by ruzko** [sssemil/waydroid_geoclue_bridge#1]
Cool project! 

What's needed to make it work?
Doing `cargo run` makes it output `setting listener` and `starting client`, but nothing afterwards. Other apps on my system use geoclue without problems.

Is the project in a non-working state, or do I need to o something more? 

**environment**
OS: PostmarketOS 24.06 (alpine)
RUSTFLAGS: -C target-feature=-crt-static
geoclue version: 2.7.1
source edits: changed WAYDROD_LOCATION_PATH to "/home/user/gps/location_data.json" for testing purposes since waydroid/rootfs/tmp is read-only/owned by root.

**Comment by sssemil** [comment]
It was never finished, sorry

**Comment by ruzko** [comment]
That's alright.
I ended up scripting something rudimentary with similar UX in shell, since I needed something quick while out hunting. [geobridge](https://gitlab.com/papiris/geobridge) if you want to check it out.
